# Generated by Django 3.2.16 on 2022-10-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221024_0807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
